<a href="https://colab.research.google.com/github/Navyareddy1124/Python_Frameworks/blob/main/Pandas_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
sales_data=pd.read_csv(r'/content/drive/MyDrive/CSV files - KSRD/Advanced_Dirty_Sales_Dataset.csv')

In [4]:
sales_data.head(10)

,OrderID,CustomerID,CustomerName,Product,Category,Quantity,Price,OrderDate,City,Region,Returned,TotalAmount
0,44770,8192,@ charlie !,Keyboard,Electronics,1,$870.54,32/13/2023,PHOENIX#123,South,False,870.54
1,23355,9138,@ charlie !,Monitor,Electronics,5,$144.02,05-02-2024,HOUSTON#123,West,False,720.1
2,75847,4098,@ charlie !,Laptop,Accessories,3,$557.79,11/08/2024,NEW YORK#123,East,False,1673.37
3,95176,2391,@ eva !,Monitor,Electronics,5,$552.2,32/13/2023,CHICAGO#123,North,False,2761.0
4,1854,8842,@ eva !,Laptop,Accessories,4,$411.2,32/13/2023,CHICAGO#123,East,False,1644.8
5,56788,6935,@ david !,Monitor,Electronics,1,$415.12,"October 06, 2024",LOS ANGELES#123,West,False,415.12
6,63473,2787,@ bob !,Tablet,Electronics,3,$677.7,"April 03, 2024",PHOENIX#123,West,False,2033.1
7,79506,3389,@ alice !,Phone,Accessories,9,$674.73,"July 14, 2024",HOUSTON#123,North,True,6072.57
8,55148,1287,@ david !,Laptop,Accessories,2,$330.38,09-01-2024,HOUSTON#123,East,False,660.76
9,24564,3745,@ bob !,Tablet,Accessories,8,$686.34,23/04/2023,PHOENIX#123,North,False,5490.72

In [5]:
demo_sales=pd.read_csv(r"/content/drive/MyDrive/CSV files - KSRD/Advanced_Dirty_Demographics_Dataset.csv")

In [6]:
demo_sales.head()

,CustomerID,CustomerName,City,Region,Age,Gender,IncomeBracket,MaritalStatus
0,3461,EVA,Los Angeles,West,41,male!,$LOW,married##
1,1755,CHARLIE,Chicago,West,48,male!,$HIGH,married##
2,1693,BOB,Phoenix,East,21,femle!,$MIDDEL,married##
3,9880,BOB,Houston,West,58,femle!,$MIDDEL,divorced##
4,2529,BOB,Los Angeles,North,26,femle!,$MIDDEL,divorced##

In [7]:
 #Load the dataset and print the shape, column names, and data types
shape=sales_data.shape
print(shape)                    #shape
print(sales_data.columns)       #column names
print(sales_data.dtypes)        #data types

(100100, 12)
Index(['OrderID', 'CustomerID', 'CustomerName', 'Product', 'Category',
       'Quantity', 'Price', 'OrderDate', 'City', 'Region', 'Returned',
       'TotalAmount'],
      dtype='object')
OrderID          int64
CustomerID       int64
CustomerName    object
Product         object
Category        object
Quantity        object
Price           object
OrderDate       object
City            object
Region          object
Returned          bool
TotalAmount     object
dtype: object

In [8]:
#Show the first 10 and last 10 rows of the dataset.
sales_data.head(10)          # first 10 rows

,OrderID,CustomerID,CustomerName,Product,Category,Quantity,Price,OrderDate,City,Region,Returned,TotalAmount
0,44770,8192,@ charlie !,Keyboard,Electronics,1,$870.54,32/13/2023,PHOENIX#123,South,False,870.54
1,23355,9138,@ charlie !,Monitor,Electronics,5,$144.02,05-02-2024,HOUSTON#123,West,False,720.1
2,75847,4098,@ charlie !,Laptop,Accessories,3,$557.79,11/08/2024,NEW YORK#123,East,False,1673.37
3,95176,2391,@ eva !,Monitor,Electronics,5,$552.2,32/13/2023,CHICAGO#123,North,False,2761.0
4,1854,8842,@ eva !,Laptop,Accessories,4,$411.2,32/13/2023,CHICAGO#123,East,False,1644.8
5,56788,6935,@ david !,Monitor,Electronics,1,$415.12,"October 06, 2024",LOS ANGELES#123,West,False,415.12
6,63473,2787,@ bob !,Tablet,Electronics,3,$677.7,"April 03, 2024",PHOENIX#123,West,False,2033.1
7,79506,3389,@ alice !,Phone,Accessories,9,$674.73,"July 14, 2024",HOUSTON#123,North,True,6072.57
8,55148,1287,@ david !,Laptop,Accessories,2,$330.38,09-01-2024,HOUSTON#123,East,False,660.76
9,24564,3745,@ bob !,Tablet,Accessories,8,$686.34,23/04/2023,PHOENIX#123,North,False,5490.72

In [9]:
sales_data.tail(10)

,OrderID,CustomerID,CustomerName,Product,Category,Quantity,Price,OrderDate,City,Region,Returned,TotalAmount
100090,87473,6459,@ eva !,Phone,Electronics,7,$971.5,12/10/2023,PHOENIX#123,South,False,6800.5
100091,46252,4130,@ bob !,Phone,Accessories,7,$348.02,2024-06-01,CHICAGO#123,South,False,2436.14
100092,6769,5466,@ eva !,Keyboard,Accessories,3,$752.28,2023-08-09,LOS ANGELES#123,West,False,2256.84
100093,29838,8422,@ eva !,Monitor,NaN,8,$302.33,09/04/2023,CHICAGO#123,South,False,2418.64
100094,40937,2341,@ eva !,Tablet,Accessories,4,$736.55,"March 12, 2024",NEW YORK#123,East,True,2946.2
100095,95426,5376,@ alice !,Keyboard,Electronics,2,$468.67,2023-08-14,NaN,West,False,937.34
100096,77181,6047,@ alice !,Keyboard,Accessories,5,$1350.58,32/13/2023,CHICAGO#123,South,True,6752.9
100097,7354,2439,@ bob !,Laptop,Electronics,8,$330.46,2024-10-05,LOS ANGELES#123,East,False,2643.68
100098,52126,2810,@ alice !,Keyboard,Electronics,7,$361.9,"October 22, 2023",NEW YORK#123,West,False,2533.3
100099,80766,5705,@ david !,Tablet,Electronics,1,$760.99,26/03/2023,CHICAGO#123,North,False,760.99

In [10]:
#Convert OrderDate to datetime
sales_data['OrderDate'] = pd.to_datetime(sales_data['OrderDate'], errors='coerce')
print(sales_data.dtypes)

/tmp/ipython-input-437056762.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  sales_data['OrderDate'] = pd.to_datetime(sales_data['OrderDate'], errors='coerce')

OrderID                  int64
CustomerID               int64
CustomerName            object
Product                 object
Category                object
Quantity                object
Price                   object
OrderDate       datetime64[ns]
City                    object
Region                  object
Returned                  bool
TotalAmount             object
dtype: object

In [11]:
#Display the total number of unique customers.
unique_customers=sales_data["CustomerID"].nunique()
print(unique_customers)

8999

In [12]:
# Show all unique product categories and count them.
unique_categories = sales_data["Category"].unique()
print(unique_categories)
print("Count of unique categories:", len(unique_categories))

['Electronics' 'Accessories' nan]
Count of unique categories: 3

In [13]:
# Filter all orders made in the city of "Los Angeles
los_angles_orders=sales_data[sales_data["City"]=="Los Angeles"]
print(los_angles_orders)

Empty DataFrame
Columns: [OrderID, CustomerID, CustomerName, Product, Category, Quantity, Price, OrderDate, City, Region, Returned, TotalAmount]
Index: []

In [14]:
sales_data['Quantity'] = pd.to_numeric(sales_data['Quantity'], errors='coerce')
count=sales_data[sales_data["Quantity"] > 5]
print(count)

        OrderID  CustomerID CustomerName   Product     Category  Quantity  \
7         79506        3389    @ alice !     Phone  Accessories       9.0
9         24564        3745      @ bob !    Tablet  Accessories       8.0
13        69640        1481      @ bob !     Phone  Accessories       6.0
17        23495        1514      @ bob !    Tablet  Electronics       9.0
18        86339        3999      @ eva !    Laptop  Electronics       9.0
...         ...         ...          ...       ...          ...       ...
100090    87473        6459      @ eva !     Phone  Electronics       7.0
100091    46252        4130      @ bob !     Phone  Accessories       7.0
100093    29838        8422      @ eva !   Monitor          NaN       8.0
100097     7354        2439      @ bob !    Laptop  Electronics       8.0
100098    52126        2810    @ alice !  Keyboard  Electronics       7.0

           Price  OrderDate             City Region  Returned TotalAmount
7        $674.73 2024-07-14      HOUSTON#123  North      True     6072.57
9        $686.34 2023-04-23      PHOENIX#123  North     False     5490.72
13       $173.41 2023-11-26      HOUSTON#123   West     False     1040.46
17       $212.04 2023-07-09      CHICAGO#123   East     False     1908.36
18      $1070.42 2024-04-29  LOS ANGELES#123   West     False     9633.78
...          ...        ...              ...    ...       ...         ...
100090    $971.5 2023-12-10      PHOENIX#123  South     False      6800.5
100091   $348.02 2024-06-01      CHICAGO#123  South     False     2436.14
100093   $302.33 2023-09-04      CHICAGO#123  South     False     2418.64
100097   $330.46 2024-10-05  LOS ANGELES#123   East     False     2643.68
100098    $361.9 2023-10-22     NEW YORK#123   West     False      2533.3

[43860 rows x 12 columns]

In [15]:
#Add a new column UnitTotal = Quantity * Price and compare with TotalAmount.
sales_data['Price'] = sales_data['Price'].str.replace('$', '', regex=False).astype(float)
sales_data['UnitTotal'] = sales_data['Quantity'] * sales_data['Price']
print(sales_data)

        OrderID  CustomerID CustomerName   Product     Category  Quantity  \
0         44770        8192  @ charlie !  Keyboard  Electronics       1.0
1         23355        9138  @ charlie !   Monitor  Electronics       5.0
2         75847        4098  @ charlie !    Laptop  Accessories       3.0
3         95176        2391      @ eva !   Monitor  Electronics       5.0
4          1854        8842      @ eva !    Laptop  Accessories       4.0
...         ...         ...          ...       ...          ...       ...
100095    95426        5376    @ alice !  Keyboard  Electronics       2.0
100096    77181        6047    @ alice !  Keyboard  Accessories       5.0
100097     7354        2439      @ bob !    Laptop  Electronics       8.0
100098    52126        2810    @ alice !  Keyboard  Electronics       7.0
100099    80766        5705    @ david !    Tablet  Electronics       1.0

          Price  OrderDate             City Region  Returned TotalAmount  \
0        870.54        NaT      PHOENIX#123  South     False      870.54
1        144.02 2024-05-02      HOUSTON#123   West     False       720.1
2        557.79 2024-11-08     NEW YORK#123   East     False     1673.37
3        552.20        NaT      CHICAGO#123  North     False      2761.0
4        411.20        NaT      CHICAGO#123   East     False      1644.8
...         ...        ...              ...    ...       ...         ...
100095   468.67 2023-08-14              NaN   West     False      937.34
100096  1350.58        NaT      CHICAGO#123  South      True      6752.9
100097   330.46 2024-10-05  LOS ANGELES#123   East     False     2643.68
100098   361.90 2023-10-22     NEW YORK#123   West     False      2533.3
100099   760.99 2023-03-26      CHICAGO#123  North     False      760.99

        UnitTotal
0          870.54
1          720.10
2         1673.37
3         2761.00
4         1644.80
...           ...
100095     937.34
100096    6752.90
100097    2643.68
100098    2533.30
100099     760.99

[100100 rows x 13 columns]

In [16]:
sales_data['TotalAmount'] = pd.to_numeric(sales_data['TotalAmount'], errors='coerce')
sales_data['DiscountApplied'] = sales_data['UnitTotal'] > sales_data['TotalAmount']
print(sales_data)

        OrderID  CustomerID CustomerName   Product     Category  Quantity  \
0         44770        8192  @ charlie !  Keyboard  Electronics       1.0
1         23355        9138  @ charlie !   Monitor  Electronics       5.0
2         75847        4098  @ charlie !    Laptop  Accessories       3.0
3         95176        2391      @ eva !   Monitor  Electronics       5.0
4          1854        8842      @ eva !    Laptop  Accessories       4.0
...         ...         ...          ...       ...          ...       ...
100095    95426        5376    @ alice !  Keyboard  Electronics       2.0
100096    77181        6047    @ alice !  Keyboard  Accessories       5.0
100097     7354        2439      @ bob !    Laptop  Electronics       8.0
100098    52126        2810    @ alice !  Keyboard  Electronics       7.0
100099    80766        5705    @ david !    Tablet  Electronics       1.0

          Price  OrderDate             City Region  Returned  TotalAmount  \
0        870.54        NaT      PHOENIX#123  South     False       870.54
1        144.02 2024-05-02      HOUSTON#123   West     False       720.10
2        557.79 2024-11-08     NEW YORK#123   East     False      1673.37
3        552.20        NaT      CHICAGO#123  North     False      2761.00
4        411.20        NaT      CHICAGO#123   East     False      1644.80
...         ...        ...              ...    ...       ...          ...
100095   468.67 2023-08-14              NaN   West     False       937.34
100096  1350.58        NaT      CHICAGO#123  South      True      6752.90
100097   330.46 2024-10-05  LOS ANGELES#123   East     False      2643.68
100098   361.90 2023-10-22     NEW YORK#123   West     False      2533.30
100099   760.99 2023-03-26      CHICAGO#123  North     False       760.99

        UnitTotal  DiscountApplied
0          870.54            False
1          720.10            False
2         1673.37            False
3         2761.00            False
4         1644.80            False
...           ...              ...
100095     937.34            False
100096    6752.90            False
100097    2643.68            False
100098    2533.30            False
100099     760.99            False

[100100 rows x 14 columns]

In [17]:
#Drop the column DiscountApplied after saving it to a variable
saved_discount = sales_data['DiscountApplied'].copy()
sales = sales_data.drop(columns=['DiscountApplied'])
print(saved_discount)

0         False
1         False
2         False
3         False
4         False
          ...
100095    False
100096    False
100097    False
100098    False
100099    False
Name: DiscountApplied, Length: 100100, dtype: bool

In [18]:
#Filter all returned orders.
print(sales_data[sales_data["Returned"]==True])

        OrderID  CustomerID CustomerName   Product     Category  Quantity  \
7         79506        3389    @ alice !     Phone  Accessories       9.0
15         5103        1382      @ eva !     Phone  Accessories       1.0
21        87250        2818    @ alice !     Phone  Electronics       3.0
31        81349        3421      @ eva !    Laptop  Accessories       7.0
53        50549        8174      @ eva !   Monitor  Electronics       5.0
...         ...         ...          ...       ...          ...       ...
100031    53849        7723    @ alice !  Keyboard  Electronics       4.0
100041    94461        5550  @ charlie !  Keyboard  Electronics       7.0
100061    48148        6197      @ bob !    Tablet  Accessories       3.0
100094    40937        2341      @ eva !    Tablet  Accessories       4.0
100096    77181        6047    @ alice !  Keyboard  Accessories       5.0

          Price  OrderDate             City Region  Returned  TotalAmount  \
7        674.73 2024-07-14      HOUSTON#123  North      True      6072.57
15       504.94 2023-03-07     NEW YORK#123   West      True       504.94
21      1188.93 2024-02-27  LOS ANGELES#123  North      True      3566.79
31      1383.91 2024-05-18  LOS ANGELES#123   West      True      9687.37
53      1358.43        NaT      HOUSTON#123  South      True      6792.15
...         ...        ...              ...    ...       ...          ...
100031   947.33 2023-04-14      CHICAGO#123  North      True      3789.32
100041  1479.18 2023-05-29      PHOENIX#123   East      True     10354.26
100061   670.62 2024-09-13  LOS ANGELES#123  South      True      2011.86
100094   736.55 2024-03-12     NEW YORK#123   East      True      2946.20
100096  1350.58        NaT      CHICAGO#123  South      True      6752.90

        UnitTotal  DiscountApplied
7         6072.57            False
15         504.94            False
21        3566.79            False
31        9687.37            False
53        6792.15            False
...           ...              ...
100031    3789.32            False
100041   10354.26            False
100061    2011.86             True
100094    2946.20            False
100096    6752.90            False

[9873 rows x 14 columns]

In [19]:
#Top 5 cities by number of orders
top_cities = sales_data['City'].value_counts().head(5)
print(top_cities)

City
NEW YORK#123       19781
PHOENIX#123        19771
CHICAGO#123        19615
LOS ANGELES#123    19519
HOUSTON#123        19412
Name: count, dtype: int64

In [20]:
#Top 3 most sold products (by quantity)
result=sales_data.groupby("Product")["Quantity"].sum().sort_values(ascending=False).head(3)
print(result)

Product
Phone       97697.0
Laptop      97501.0
Keyboard    96835.0
Name: Quantity, dtype: float64

In [21]:
#Rename CustomerName to CustName and revert it
sales_data.rename(columns={'CustomerName': 'CustName'}, inplace=True)
print("before rename---",sales_data)
# revert back
rev_back=sales_data.rename(columns={'CustName': 'CustomerName'}, inplace=True)
print("after reverting back--- ",sales_data)

before rename---         OrderID  CustomerID     CustName   Product     Category  Quantity  \
0         44770        8192  @ charlie !  Keyboard  Electronics       1.0
1         23355        9138  @ charlie !   Monitor  Electronics       5.0
2         75847        4098  @ charlie !    Laptop  Accessories       3.0
3         95176        2391      @ eva !   Monitor  Electronics       5.0
4          1854        8842      @ eva !    Laptop  Accessories       4.0
...         ...         ...          ...       ...          ...       ...
100095    95426        5376    @ alice !  Keyboard  Electronics       2.0
100096    77181        6047    @ alice !  Keyboard  Accessories       5.0
100097     7354        2439      @ bob !    Laptop  Electronics       8.0
100098    52126        2810    @ alice !  Keyboard  Electronics       7.0
100099    80766        5705    @ david !    Tablet  Electronics       1.0

          Price  OrderDate             City Region  Returned  TotalAmount  \
0        870.54        NaT      PHOENIX#123  South     False       870.54
1        144.02 2024-05-02      HOUSTON#123   West     False       720.10
2        557.79 2024-11-08     NEW YORK#123   East     False      1673.37
3        552.20        NaT      CHICAGO#123  North     False      2761.00
4        411.20        NaT      CHICAGO#123   East     False      1644.80
...         ...        ...              ...    ...       ...          ...
100095   468.67 2023-08-14              NaN   West     False       937.34
100096  1350.58        NaT      CHICAGO#123  South      True      6752.90
100097   330.46 2024-10-05  LOS ANGELES#123   East     False      2643.68
100098   361.90 2023-10-22     NEW YORK#123   West     False      2533.30
100099   760.99 2023-03-26      CHICAGO#123  North     False       760.99

        UnitTotal  DiscountApplied
0          870.54            False
1          720.10            False
2         1673.37            False
3         2761.00            False
4         1644.80            False
...           ...              ...
100095     937.34            False
100096    6752.90            False
100097    2643.68            False
100098    2533.30            False
100099     760.99            False

[100100 rows x 14 columns]
after reverting back---          OrderID  CustomerID CustomerName   Product     Category  Quantity  \
0         44770        8192  @ charlie !  Keyboard  Electronics       1.0
1         23355        9138  @ charlie !   Monitor  Electronics       5.0
2         75847        4098  @ charlie !    Laptop  Accessories       3.0
3         95176        2391      @ eva !   Monitor  Electronics       5.0
4          1854        8842      @ eva !    Laptop  Accessories       4.0
...         ...         ...          ...       ...          ...       ...
100095    95426        5376    @ alice !  Keyboard  Electronics       2.0
100096    77181        6047    @ alice !  Keyboard  Accessories       5.0
100097     7354        2439      @ bob !    Laptop  Electronics       8.0
100098    52126        2810    @ alice !  Keyboard  Electronics       7.0
100099    80766        5705    @ david !    Tablet  Electronics       1.0

          Price  OrderDate             City Region  Returned  TotalAmount  \
0        870.54        NaT      PHOENIX#123  South     False       870.54
1        144.02 2024-05-02      HOUSTON#123   West     False       720.10
2        557.79 2024-11-08     NEW YORK#123   East     False      1673.37
3        552.20        NaT      CHICAGO#123  North     False      2761.00
4        411.20        NaT      CHICAGO#123   East     False      1644.80
...         ...        ...              ...    ...       ...          ...
100095   468.67 2023-08-14              NaN   West     False       937.34
100096  1350.58        NaT      CHICAGO#123  South      True      6752.90
100097   330.46 2024-10-05  LOS ANGELES#123   East     False      2643.68
100098   361.90 2023-10-22     NEW YORK#123   West     False      2533.30
100099   760.99 2023-03-26      CHICAGO#123  North     False       760.99

        UnitTotal  DiscountApplied
0          870.54            False
1          720.10            False
2         1673.37            False
3         2761.00            False
4         1644.80            False
...           ...              ...
100095     937.34            False
100096    6752.90            False
100097    2643.68            False
100098    2533.30            False
100099     760.99            False

[100100 rows x 14 columns]

In [22]:
#Check and count missing values in each column
missing_values=sales.isnull().sum()
print(missing_values)

OrderID             0
CustomerID          0
CustomerName        0
Product          2001
Category         2003
Quantity         1001
Price            1001
OrderDate       20072
City             2002
Region              0
Returned            0
TotalAmount      1001
UnitTotal        1001
dtype: int64

In [23]:
#Fill missing City values with "Unknown"
sales_data['City'] = sales_data['City'].fillna("Unknown")
print(sales_data["City"])

0             PHOENIX#123
1             HOUSTON#123
2            NEW YORK#123
3             CHICAGO#123
4             CHICAGO#123
               ...
100095            Unknown
100096        CHICAGO#123
100097    LOS ANGELES#123
100098       NEW YORK#123
100099        CHICAGO#123
Name: City, Length: 100100, dtype: object

In [24]:
#Remove duplicates based on OrderID
sales_data = sales_data.drop_duplicates(subset='OrderID')
print(sales_data["OrderID"])

0         44770
1         23355
2         75847
3         95176
4          1854
          ...
100095    95426
100096    77181
100097     7354
100098    52126
100099    80766
Name: OrderID, Length: 100000, dtype: int64

In [25]:
#Sort by TotalAmount (descending)
sorted_res=sales_data.sort_values(by='TotalAmount', ascending=False)
print(sorted_res)

       OrderID  CustomerID CustomerName   Product     Category  Quantity  \
99875    78404        2864      @ bob !    Laptop  Accessories       9.0
47882    27909        1707    @ david !   Monitor  Electronics       9.0
75618    63782        7708    @ david !  Keyboard  Electronics       9.0
55578    49344        4338    @ david !  Keyboard  Electronics       9.0
53794    34029        3759      @ bob !    Laptop  Electronics       9.0
...        ...         ...          ...       ...          ...       ...
99302     6464        6738    @ david !    Tablet  Electronics       NaN
99371    17207        5753  @ charlie !     Phone  Electronics       NaN
99529    29355        9833      @ eva !  Keyboard  Accessories       NaN
99630    86382        8146      @ bob !     Phone  Electronics       NaN
99845    11862        8008      @ eva !    Tablet  Electronics       NaN

         Price  OrderDate             City Region  Returned  TotalAmount  \
99875  1499.99 2024-07-06      PHOENIX#123   West     False     13499.91
47882  1499.95 2024-01-28      CHICAGO#123   West     False     13499.55
75618  1499.74 2024-06-07     NEW YORK#123   West     False     13497.66
55578  1499.20 2023-02-13     NEW YORK#123  South     False     13492.80
53794  1499.17        NaT      PHOENIX#123   East     False     13492.53
...        ...        ...              ...    ...       ...          ...
99302      NaN 2024-04-15  LOS ANGELES#123  North     False          NaN
99371      NaN        NaT      HOUSTON#123  South     False          NaN
99529      NaN 2023-05-30     NEW YORK#123   West     False          NaN
99630      NaN        NaT      HOUSTON#123   East     False          NaN
99845      NaN 2023-03-03     NEW YORK#123  North     False          NaN

       UnitTotal  DiscountApplied
99875   13499.91            False
47882   13499.55             True
75618   13497.66            False
55578   13492.80             True
53794   13492.53            False
...          ...              ...
99302        NaN            False
99371        NaN            False
99529        NaN            False
99630        NaN            False
99845        NaN            False

[100000 rows x 14 columns]

In [26]:
#Top 5 orders with highest total amount
print(sales.sort_values('TotalAmount', ascending=False).head(5))

       OrderID  CustomerID CustomerName   Product     Category  Quantity  \
99875    78404        2864      @ bob !    Laptop  Accessories       9.0
47882    27909        1707    @ david !   Monitor  Electronics       9.0
75618    63782        7708    @ david !  Keyboard  Electronics       9.0
55578    49344        4338    @ david !  Keyboard  Electronics       9.0
53794    34029        3759      @ bob !    Laptop  Electronics       9.0

         Price  OrderDate          City Region  Returned  TotalAmount  \
99875  1499.99 2024-07-06   PHOENIX#123   West     False     13499.91
47882  1499.95 2024-01-28   CHICAGO#123   West     False     13499.55
75618  1499.74 2024-06-07  NEW YORK#123   West     False     13497.66
55578  1499.20 2023-02-13  NEW YORK#123  South     False     13492.80
53794  1499.17        NaT   PHOENIX#123   East     False     13492.53

       UnitTotal
99875   13499.91
47882   13499.55
75618   13497.66
55578   13492.80
53794   13492.53

In [27]:
#Extract Year and Month from OrderDate
sales_data['Year'] = sales_data['OrderDate'].dt.year
sales_data['Month'] = sales_data['OrderDate'].dt.month
print(sales_data['Year'],sales_data['Month'])

0            NaN
1         2024.0
2         2024.0
3            NaN
4            NaN
           ...
100095    2023.0
100096       NaN
100097    2024.0
100098    2023.0
100099    2023.0
Name: Year, Length: 100000, dtype: float64 0          NaN
1          5.0
2         11.0
3          NaN
4          NaN
          ...
100095     8.0
100096     NaN
100097    10.0
100098    10.0
100099     3.0
Name: Month, Length: 100000, dtype: float64

In [28]:
#Create a new column OrderMonth with full month name
sales_data['OrderMonth'] = sales_data['OrderDate'].dt.strftime('%B')
print(sales_data["OrderMonth"])

0              NaN
1              May
2         November
3              NaN
4              NaN
            ...
100095      August
100096         NaN
100097     October
100098     October
100099       March
Name: OrderMonth, Length: 100000, dtype: object

In [29]:
#Show all Q1 (Jan–Mar) orders
q1_orders = sales_data[(sales_data['Month'] >= 1) & (sales_data['Month'] <= 3)]
print(q1_orders)

        OrderID  CustomerID CustomerName   Product     Category  Quantity  \
15         5103        1382      @ eva !     Phone  Accessories       1.0
21        87250        2818    @ alice !     Phone  Electronics       3.0
24        90538        2124    @ david !  Keyboard  Accessories       4.0
43        48638        4913  @ charlie !    Tablet  Electronics       3.0
49        66090        6049    @ david !  Keyboard  Electronics       6.0
...         ...         ...          ...       ...          ...       ...
100074    79782        9365    @ david !    Laptop  Accessories       5.0
100082    44707        7179  @ charlie !  Keyboard  Electronics       9.0
100088    50567        7478  @ charlie !   Monitor  Accessories       3.0
100094    40937        2341      @ eva !    Tablet  Accessories       4.0
100099    80766        5705    @ david !    Tablet  Electronics       1.0

          Price  OrderDate             City Region  Returned  TotalAmount  \
15       504.94 2023-03-07     NEW YORK#123   West      True       504.94
21      1188.93 2024-02-27  LOS ANGELES#123  North      True      3566.79
24       898.16 2023-03-01      PHOENIX#123   West     False      3592.64
43       330.45 2024-01-12  LOS ANGELES#123   East     False       991.35
49       822.84 2024-02-22  LOS ANGELES#123  South     False      4937.04
...         ...        ...              ...    ...       ...          ...
100074  1368.47 2023-01-12  LOS ANGELES#123   West     False      6842.35
100082  1125.69 2023-02-22      PHOENIX#123   East     False     10131.21
100088   569.70 2023-01-07      HOUSTON#123  North     False      1709.10
100094   736.55 2024-03-12     NEW YORK#123   East      True      2946.20
100099   760.99 2023-03-26      CHICAGO#123  North     False       760.99

        UnitTotal  DiscountApplied    Year  Month OrderMonth
15         504.94            False  2023.0    3.0      March
21        3566.79            False  2024.0    2.0   February
24        3592.64            False  2023.0    3.0      March
43         991.35            False  2024.0    1.0    January
49        4937.04            False  2024.0    2.0   February
...           ...              ...     ...    ...        ...
100074    6842.35            False  2023.0    1.0    January
100082   10131.21             True  2023.0    2.0   February
100088    1709.10             True  2023.0    1.0    January
100094    2946.20            False  2024.0    3.0      March
100099     760.99            False  2023.0    3.0      March

[19726 rows x 17 columns]

In [30]:
#Number of orders for each region
sales_data['Region'].value_counts()

Region
East     25098
North    25022
South    24998
West     24882
Name: count, dtype: int64

In [31]:
#Customers who bought BOTH "Phone" and "Laptop"
phone_customers = set(sales_data[sales_data['Product'] == 'Phone']['CustomerID'])
laptop_customers = set(sales_data[sales_data['Product'] == 'Laptop']['CustomerID'])
both=phone_customers.intersection(laptop_customers)
print(both)

{1000, 1001, 1003, 1004, 1005, 1006, 1007, 1008, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1030, 1031, 1032, 1033, 1034, 1036, 1037, 1039, 1040, 1041, 1043, 1045, 1048, 1049, 1050, 1051, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1066, 1067, 1068, 1070, 1071, 1072, 1073, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1089, 1090, 1091, 1092, 1095, 1096, 1097, 1098, 1099, 1100, 1101, 1103, 1104, 1106, 1108, 1109, 1110, 1111, 1112, 1113, 1116, 1117, 1118, 1119, 1121, 1122, 1123, 1125, 1126, 1127, 1130, 1132, 1133, 1135, 1137, 1139, 1140, 1141, 1142, 1145, 1146, 1148, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1157, 1158, 1160, 1161, 1162, 1163, 1164, 1167, 1169, 1170, 1171, 1173, 1177, 1178, 1180, 1181, 1182, 1183, 1184, 1185, 1187, 1188, 1189, 1191, 1192, 1193, 1198, 1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210, 1211, 1213, 1215, 1219, 1220, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231, 1232, 1233, 1234, 1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243, 1244, 1245, 1247, 1249, 1252, 1254, 1255, 1256, 1257, 1258, 1259, 1260, 1261, 1263, 1264, 1265, 1266, 1267, 1268, 1269, 1270, 1272, 1275, 1276, 1277, 1278, 1279, 1280, 1281, 1282, 1284, 1285, 1288, 1289, 1290, 1291, 1292, 1293, 1294, 1295, 1296, 1297, 1298, 1299, 1301, 1302, 1303, 1305, 1306, 1308, 1312, 1313, 1315, 1316, 1318, 1321, 1322, 1324, 1325, 1326, 1327, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1341, 1343, 1344, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1356, 1357, 1358, 1359, 1361, 1362, 1363, 1364, 1366, 1367, 1368, 1369, 1370, 1371, 1373, 1374, 1375, 1377, 1378, 1379, 1381, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1391, 1392, 1393, 1395, 1396, 1397, 1398, 1399, 1401, 1402, 1403, 1404, 1406, 1407, 1408, 1409, 1410, 1411, 1412, 1413, 1414, 1416, 1418, 1419, 1420, 1421, 1422, 1425, 1427, 1428, 1429, 1430, 1432, 1433, 1434, 1435, 1436, 1438, 1440, 1442, 1443, 1445, 1446, 1448, 1449, 1450, 1451, 1452, 1453, 1454, 1455, 1456, 1458, 1459, 1460, 1461, 1462, 1464, 1467, 1468, 1469, 1470, 1471, 1472, 1473, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1483, 1484, 1485, 1488, 1489, 1490, 1491, 1492, 1495, 1496, 1497, 1498, 1500, 1502, 1503, 1504, 1506, 1507, 1508, 1509, 1510, 1511, 1512, 1513, 1514, 1515, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1530, 1531, 1532, 1533, 1534, 1535, 1536, 1537, 1538, 1539, 1540, 1542, 1543, 1544, 1545, 1546, 1547, 1548, 1551, 1553, 1554, 1555, 1557, 1558, 1559, 1561, 1562, 1563, 1564, 1565, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1576, 1577, 1578, 1579, 1580, 1581, 1582, 1583, 1584, 1586, 1587, 1588, 1589, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1599, 1600, 1601, 1602, 1603, 1604, 1605, 1608, 1609, 1610, 1611, 1612, 1613, 1614, 1615, 1617, 1618, 1620, 1622, 1624, 1625, 1627, 1628, 1629, 1630, 1631, 1633, 1634, 1635, 1637, 1638, 1639, 1640, 1641, 1643, 1644, 1645, 1648, 1649, 1650, 1652, 1653, 1654, 1656, 1658, 1659, 1661, 1663, 1664, 1665, 1666, 1667, 1668, 1671, 1672, 1674, 1675, 1676, 1677, 1678, 1679, 1680, 1682, 1683, 1685, 1686, 1688, 1689, 1690, 1692, 1693, 1695, 1696, 1697, 1698, 1699, 1701, 1702, 1703, 1704, 1707, 1708, 1709, 1711, 1712, 1714, 1715, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1732, 1733, 1734, 1735, 1736, 1737, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1759, 1760, 1761, 1762, 1763, 1765, 1767, 1770, 1771, 1773, 1774, 1775, 1776, 1777, 1778, 1779, 1780, 1781, 1783, 1785, 1786, 1787, 1788, 1789, 1791, 1792, 1793, 1794, 1795, 1797, 1798, 1799, 1800, 1801, 1802, 1803, 1805, 1806, 1808, 1809, 1810, 1811, 1812, 1814, 1815, 1816, 1817, 1818, 1819, 1820, 1822, 1823, 1824, 1825, 1827, 1828, 1829, 1831, 1833, 1834, 1836, 1837, 1838, 1839, 1844, 1845, 1846, 1847, 1848, 1850, 1851, 1853, 1854, 1855, 1858, 1859, 1860, 1861, 1862, 1864, 1865, 1867, 1870, 1871, 1873, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890, 1892, 1895, 1896, 1897, 1899, 1900, 1901, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1918, 1919, 1920, 1922, 1924, 1925, 1927, 1928, 1929, 1930, 1932, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1966, 1967, 1968, 1969, 1970, 1971, 1973, 1974, 1976, 1977, 1978, 1979, 1980, 1981, 1983, 1984, 1987, 1988, 1990, 1991, 1992, 1993, 1994, 1995, 1997, 1998, 1999, 2000, 2002, 2003, 2005, 2007, 2009, 2010, 2011, 2012, 2014, 2015, 2016, 2017, 2018, 2019, 2022, 2024, 2025, 2026, 2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035, 2036, 2037, 2039, 2040, 2041, 2043, 2044, 2045, 2046, 2047, 2048, 2050, 2051, 2052, 2054, 2056, 2058, 2059, 2060, 2061, 2064, 2065, 2067, 2068, 2069, 2070, 2072, 2073, 2074, 2075, 2076, 2077, 2078, 2079, 2080, 2081, 2082, 2083, 2084, 2085, 2086, 2087, 2088, 2089, 2091, 2092, 2093, 2094, 2095, 2096, 2097, 2098, 2099, 2100, 2101, 2102, 2103, 2104, 2105, 2106, 2107, 2108, 2109, 2110, 2111, 2113, 2115, 2116, 2117, 2118, 2119, 2121, 2122, 2123, 2124, 2125, 2126, 2127, 2129, 2130, 2131, 2132, 2133, 2134, 2135, 2136, 2137, 2138, 2140, 2141, 2143, 2144, 2145, 2146, 2147, 2148, 2149, 2150, 2151, 2152, 2153, 2155, 2156, 2157, 2158, 2159, 2160, 2161, 2166, 2167, 2168, 2169, 2170, 2173, 2177, 2180, 2181, 2182, 2183, 2184, 2185, 2186, 2190, 2192, 2193, 2194, 2195, 2196, 2197, 2198, 2200, 2201, 2202, 2203, 2204, 2205, 2207, 2208, 2209, 2210, 2212, 2213, 2214, 2215, 2216, 2217, 2218, 2220, 2222, 2223, 2224, 2225, 2226, 2227, 2230, 2231, 2232, 2233, 2234, 2235, 2236, 2237, 2238, 2239, 2240, 2241, 2242, 2244, 2245, 2246, 2247, 2248, 2249, 2250, 2251, 2253, 2254, 2256, 2258, 2260, 2261, 2262, 2263, 2264, 2265, 2266, 2267, 2268, 2269, 2270, 2271, 2275, 2276, 2277, 2278, 2279, 2280, 2281, 2282, 2286, 2287, 2288, 2289, 2290, 2291, 2292, 2293, 2294, 2295, 2296, 2297, 2298, 2299, 2300, 2301, 2304, 2306, 2307, 2308, 2309, 2310, 2311, 2312, 2313, 2314, 2315, 2316, 2317, 2320, 2321, 2324, 2325, 2327, 2329, 2330, 2331, 2332, 2334, 2336, 2337, 2338, 2339, 2340, 2342, 2343, 2344, 2345, 2346, 2347, 2348, 2349, 2350, 2351, 2352, 2353, 2356, 2357, 2358, 2359, 2360, 2361, 2364, 2365, 2366, 2367, 2368, 2369, 2371, 2373, 2374, 2375, 2376, 2377, 2378, 2379, 2381, 2382, 2383, 2385, 2386, 2387, 2388, 2391, 2392, 2393, 2395, 2397, 2398, 2400, 2401, 2403, 2404, 2405, 2406, 2407, 2409, 2410, 2411, 2415, 2416, 2417, 2418, 2419, 2421, 2422, 2423, 2425, 2426, 2427, 2428, 2429, 2431, 2432, 2433, 2434, 2436, 2437, 2438, 2439, 2440, 2445, 2446, 2448, 2450, 2451, 2452, 2454, 2455, 2456, 2457, 2458, 2459, 2460, 2461, 2462, 2463, 2464, 2465, 2466, 2468, 2469, 2471, 2473, 2474, 2475, 2476, 2477, 2479, 2480, 2481, 2482, 2484, 2485, 2487, 2488, 2490, 2492, 2493, 2494, 2495, 2496, 2497, 2500, 2501, 2502, 2505, 2506, 2507, 2508, 2509, 2511, 2513, 2515, 2516, 2518, 2522, 2525, 2526, 2529, 2530, 2531, 2532, 2534, 2535, 2536, 2537, 2538, 2539, 2540, 2543, 2544, 2545, 2547, 2548, 2550, 2551, 2552, 2553, 2554, 2555, 2556, 2557, 2558, 2559, 2560, 2562, 2563, 2564, 2565, 2566, 2567, 2568, 2570, 2571, 2573, 2574, 2577, 2578, 2579, 2580, 2581, 2582, 2584, 2585, 2586, 2587, 2588, 2589, 2590, 2591, 2592, 2594, 2595, 2596, 2597, 2598, 2600, 2601, 2602, 2603, 2604, 2605, 2606, 2607, 2608, 2609, 2610, 2611, 2612, 2613, 2614, 2615, 2616, 2617, 2619, 2620, 2621, 2622, 2623, 2624, 2625, 2626, 2627, 2629, 2630, 2632, 2633, 2634, 2635, 2636, 2637, 2638, 2639, 2641, 2642, 2643, 2645, 2646, 2648, 2649, 2650, 2651, 2653, 2654, 2655, 2656, 2657, 2658, 2660, 2664, 2665, 2666, 2667, 2668, 2673, 2674, 2675, 2676, 2677, 2679, 2680, 2681, 2682, 2683, 2685, 2686, 2688, 2689, 2691, 2692, 2693, 2695, 2697, 2698, 2699, 2701, 2703, 2705, 2706, 2707, 2709, 2710, 2712, 2713, 2714, 2715, 2716, 2717, 2718, 2719, 2720, 2721, 2722, 2725, 2726, 2728, 2729, 2730, 2733, 2734, 2735, 2736, 2737, 2738, 2739, 2741, 2743, 2744, 2745, 2746, 2747, 2748, 2749, 2750, 2751, 2753, 2754, 2755, 2756, 2757, 2759, 2760, 2761, 2762, 2763, 2764, 2766, 2767, 2769, 2770, 2771, 2772, 2773, 2775, 2777, 2778, 2779, 2780, 2781, 2782, 2783, 2784, 2785, 2787, 2788, 2789, 2790, 2791, 2792, 2793, 2795, 2797, 2798, 2800, 2802, 2803, 2804, 2805, 2806, 2809, 2810, 2811, 2812, 2813, 2815, 2816, 2817, 2818, 2819, 2820, 2821, 2823, 2825, 2826, 2827, 2828, 2829, 2830, 2831, 2832, 2833, 2834, 2835, 2836, 2838, 2840, 2841, 2842, 2843, 2844, 2845, 2846, 2848, 2849, 2850, 2851, 2852, 2854, 2857, 2858, 2859, 2861, 2862, 2863, 2864, 2867, 2868, 2869, 2870, 2871, 2873, 2874, 2875, 2876, 2877, 2878, 2881, 2883, 2884, 2886, 2887, 2888, 2889, 2892, 2893, 2894, 2896, 2897, 2898, 2900, 2901, 2902, 2903, 2904, 2905, 2908, 2909, 2910, 2911, 2912, 2914, 2915, 2916, 2917, 2918, 2919, 2920, 2921, 2922, 2923, 2924, 2925, 2926, 2927, 2928, 2930, 2931, 2932, 2933, 2934, 2935, 2936, 2939, 2940, 2942, 2943, 2944, 2945, 2946, 2947, 2948, 2949, 2950, 2951, 2952, 2954, 2955, 2957, 2958, 2959, 2960, 2961, 2963, 2964, 2965, 2966, 2967, 2969, 2971, 2972, 2973, 2974, 2975, 2976, 2977, 2978, 2979, 2980, 2981, 2982, 2984, 2985, 2986, 2989, 2990, 2991, 2992, 2993, 2994, 2995, 2996, 2997, 2998, 2999, 3000, 3001, 3002, 3003, 3005, 3007, 3009, 3010, 3011, 3012, 3014, 3015, 3016, 3017, 3019, 3020, 3021, 3023, 3024, 3025, 3026, 3027, 3028, 3029, 3030, 3031, 3032, 3033, 3034, 3035, 3036, 3037, 3038, 3039, 3040, 3042, 3044, 3046, 3047, 3048, 3049, 3050, 3051, 3052, 3053, 3054, 3055, 3056, 3057, 3058, 3059, 3060, 3061, 3062, 3063, 3064, 3065, 3068, 3069, 3070, 3071, 3073, 3074, 3076, 3078, 3079, 3082, 3083, 3084, 3085, 3086, 3087, 3088, 3089, 3090, 3091, 3092, 3093, 3094, 3096, 3097, 3098, 3099, 3101, 3108, 3109, 3110, 3112, 3113, 3114, 3115, 3116, 3117, 3120, 3121, 3122, 3123, 3124, 3125, 3126, 3127, 3129, 3130, 3131, 3132, 3134, 3135, 3137, 3138, 3139, 3143, 3144, 3145, 3146, 3147, 3148, 3151, 3153, 3154, 3155, 3156, 3157, 3158, 3160, 3161, 3162, 3166, 3169, 3170, 3171, 3172, 3173, 3174, 3175, 3176, 3177, 3178, 3180, 3181, 3183, 3185, 3187, 3190, 3191, 3193, 3194, 3195, 3196, 3197, 3198, 3199, 3200, 3201, 3202, 3203, 3204, 3205, 3207, 3208, 3212, 3214, 3215, 3216, 3217, 3219, 3221, 3222, 3224, 3225, 3226, 3227, 3228, 3229, 3230, 3231, 3233, 3234, 3235, 3237, 3238, 3239, 3240, 3241, 3242, 3243, 3245, 3246, 3247, 3248, 3249, 3250, 3251, 3252, 3253, 3254, 3256, 3259, 3261, 3262, 3263, 3264, 3265, 3266, 3269, 3270, 3271, 3272, 3273, 3274, 3275, 3276, 3278, 3279, 3280, 3281, 3282, 3283, 3284, 3285, 3286, 3287, 3288, 3289, 3291, 3292, 3293, 3294, 3295, 3296, 3297, 3298, 3299, 3300, 3301, 3302, 3303, 3304, 3305, 3306, 3307, 3308, 3309, 3311, 3312, 3313, 3314, 3315, 3317, 3318, 3319, 3320, 3321, 3322, 3324, 3325, 3326, 3327, 3329, 3330, 3331, 3332, 3333, 3335, 3336, 3337, 3338, 3339, 3340, 3341, 3343, 3345, 3346, 3347, 3348, 3349, 3350, 3351, 3353, 3354, 3356, 3357, 3358, 3359, 3362, 3363, 3364, 3365, 3366, 3367, 3368, 3369, 3370, 3371, 3372, 3373, 3374, 3375, 3376, 3377, 3379, 3380, 3382, 3383, 3384, 3385, 3386, 3387, 3389, 3390, 3391, 3392, 3394, 3395, 3396, 3397, 3398, 3399, 3400, 3401, 3402, 3404, 3405, 3406, 3407, 3408, 3409, 3410, 3411, 3412, 3413, 3414, 3416, 3417, 3418, 3419, 3421, 3422, 3423, 3424, 3425, 3426, 3427, 3428, 3429, 3430, 3432, 3433, 3435, 3436, 3437, 3438, 3439, 3440, 3443, 3444, 3445, 3447, 3449, 3452, 3453, 3454, 3456, 3457, 3460, 3461, 3462, 3463, 3465, 3466, 3467, 3469, 3470, 3471, 3472, 3473, 3474, 3475, 3477, 3478, 3479, 3481, 3482, 3483, 3484, 3485, 3486, 3489, 3490, 3491, 3492, 3493, 3494, 3496, 3499, 3500, 3503, 3504, 3505, 3506, 3508, 3509, 3510, 3511, 3512, 3513, 3515, 3518, 3520, 3521, 3524, 3525, 3526, 3527, 3529, 3530, 3531, 3532, 3533, 3534, 3535, 3536, 3537, 3538, 3539, 3541, 3542, 3543, 3544, 3545, 3547, 3548, 3549, 3550, 3551, 3552, 3555, 3556, 3557, 3559, 3560, 3561, 3562, 3563, 3564, 3565, 3566, 3567, 3568, 3569, 3570, 3571, 3574, 3576, 3577, 3578, 3579, 3580, 3581, 3583, 3585, 3586, 3587, 3589, 3590, 3591, 3592, 3593, 3594, 3595, 3597, 3598, 3599, 3600, 3602, 3603, 3604, 3605, 3608, 3609, 3610, 3611, 3612, 3614, 3615, 3617, 3618, 3619, 3620, 3621, 3622, 3623, 3624, 3625, 3626, 3627, 3628, 3629, 3630, 3631, 3632, 3633, 3634, 3636, 3639, 3640, 3642, 3645, 3646, 3648, 3649, 3650, 3651, 3652, 3653, 3655, 3657, 3659, 3660, 3661, 3662, 3663, 3665, 3668, 3669, 3670, 3671, 3672, 3673, 3674, 3675, 3676, 3677, 3678, 3679, 3680, 3681, 3682, 3685, 3686, 3687, 3689, 3691, 3692, 3695, 3696, 3698, 3699, 3701, 3702, 3703, 3704, 3705, 3708, 3709, 3710, 3711, 3712, 3714, 3715, 3716, 3718, 3721, 3722, 3723, 3724, 3725, 3727, 3728, 3729, 3730, 3731, 3732, 3733, 3735, 3736, 3737, 3738, 3739, 3740, 3741, 3743, 3745, 3746, 3747, 3748, 3749, 3750, 3752, 3753, 3754, 3755, 3756, 3757, 3758, 3759, 3760, 3761, 3762, 3763, 3766, 3767, 3768, 3769, 3770, 3771, 3772, 3773, 3774, 3775, 3776, 3778, 3779, 3780, 3781, 3782, 3785, 3786, 3787, 3788, 3789, 3790, 3793, 3794, 3795, 3796, 3797, 3800, 3801, 3802, 3804, 3806, 3807, 3808, 3809, 3810, 3811, 3813, 3814, 3815, 3816, 3817, 3818, 3819, 3820, 3821, 3823, 3824, 3825, 3826, 3829, 3830, 3832, 3835, 3836, 3838, 3839, 3840, 3841, 3842, 3843, 3844, 3845, 3846, 3849, 3850, 3851, 3852, 3853, 3857, 3858, 3859, 3860, 3862, 3863, 3864, 3865, 3866, 3868, 3869, 3870, 3871, 3873, 3877, 3878, 3879, 3880, 3882, 3883, 3884, 3886, 3887, 3888, 3891, 3892, 3894, 3895, 3896, 3897, 3899, 3902, 3903, 3904, 3905, 3906, 3907, 3908, 3909, 3910, 3911, 3914, 3915, 3916, 3917, 3918, 3919, 3920, 3921, 3922, 3923, 3924, 3925, 3926, 3927, 3929, 3931, 3932, 3933, 3934, 3935, 3936, 3937, 3938, 3939, 3940, 3941, 3942, 3944, 3945, 3947, 3948, 3949, 3950, 3951, 3952, 3953, 3954, 3955, 3957, 3958, 3961, 3962, 3963, 3964, 3965, 3966, 3967, 3968, 3969, 3970, 3971, 3972, 3974, 3975, 3976, 3977, 3978, 3979, 3981, 3983, 3984, 3985, 3986, 3987, 3989, 3990, 3991, 3993, 3994, 3995, 3996, 3997, 3999, 4000, 4001, 4002, 4003, 4005, 4006, 4007, 4008, 4011, 4012, 4013, 4014, 4015, 4016, 4017, 4018, 4019, 4020, 4021, 4022, 4023, 4024, 4026, 4027, 4028, 4029, 4030, 4032, 4034, 4036, 4037, 4041, 4042, 4043, 4044, 4045, 4047, 4048, 4049, 4050, 4051, 4052, 4053, 4054, 4055, 4056, 4057, 4059, 4060, 4061, 4065, 4067, 4068, 4069, 4070, 4071, 4072, 4073, 4074, 4076, 4079, 4080, 4081, 4082, 4083, 4085, 4086, 4087, 4088, 4089, 4090, 4091, 4092, 4093, 4097, 4098, 4099, 4101, 4102, 4103, 4105, 4107, 4108, 4109, 4110, 4111, 4113, 4114, 4115, 4116, 4117, 4118, 4119, 4120, 4121, 4122, 4123, 4125, 4126, 4127, 4128, 4130, 4134, 4135, 4136, 4138, 4141, 4142, 4143, 4145, 4146, 4147, 4149, 4150, 4151, 4152, 4153, 4154, 4155, 4156, 4158, 4160, 4162, 4163, 4164, 4165, 4166, 4167, 4169, 4170, 4171, 4172, 4173, 4174, 4175, 4176, 4177, 4178, 4179, 4180, 4182, 4183, 4184, 4185, 4186, 4187, 4189, 4190, 4191, 4193, 4194, 4195, 4196, 4197, 4199, 4201, 4202, 4203, 4204, 4205, 4206, 4207, 4211, 4212, 4213, 4215, 4216, 4218, 4219, 4220, 4223, 4224, 4225, 4226, 4227, 4228, 4229, 4230, 4231, 4232, 4233, 4234, 4237, 4238, 4239, 4240, 4241, 4242, 4243, 4244, 4245, 4246, 4247, 4248, 4249, 4250, 4251, 4253, 4254, 4255, 4256, 4257, 4258, 4260, 4261, 4262, 4264, 4266, 4267, 4268, 4270, 4271, 4272, 4273, 4275, 4276, 4277, 4278, 4282, 4283, 4284, 4285, 4286, 4289, 4291, 4292, 4293, 4294, 4296, 4298, 4299, 4300, 4301, 4303, 4304, 4307, 4308, 4309, 4310, 4311, 4312, 4313, 4314, 4316, 4318, 4320, 4322, 4323, 4324, 4325, 4326, 4328, 4329, 4330, 4331, 4333, 4334, 4336, 4337, 4338, 4341, 4342, 4343, 4344, 4345, 4346, 4347, 4349, 4350, 4351, 4354, 4355, 4356, 4357, 4358, 4359, 4360, 4361, 4362, 4363, 4364, 4365, 4368, 4369, 4370, 4371, 4372, 4373, 4374, 4375, 4376, 4377, 4378, 4379, 4380, 4381, 4384, 4386, 4388, 4389, 4390, 4391, 4393, 4398, 4399, 4404, 4406, 4407, 4408, 4409, 4412, 4413, 4414, 4415, 4416, 4417, 4418, 4419, 4421, 4422, 4424, 4425, 4426, 4428, 4429, 4430, 4431, 4432, 4433, 4435, 4436, 4437, 4438, 4439, 4440, 4441, 4443, 4445, 4446, 4447, 4448, 4449, 4450, 4451, 4452, 4453, 4454, 4456, 4457, 4458, 4460, 4461, 4462, 4464, 4465, 4467, 4468, 4470, 4472, 4473, 4474, 4475, 4476, 4477, 4478, 4479, 4481, 4482, 4483, 4484, 4485, 4486, 4487, 4488, 4489, 4490, 4492, 4493, 4495, 4496, 4497, 4498, 4499, 4500, 4501, 4503, 4504, 4505, 4506, 4507, 4508, 4509, 4510, 4511, 4512, 4514, 4515, 4516, 4517, 4518, 4519, 4520, 4522, 4523, 4524, 4525, 4526, 4527, 4528, 4530, 4531, 4532, 4534, 4536, 4537, 4538, 4540, 4541, 4542, 4543, 4545, 4547, 4548, 4549, 4550, 4551, 4552, 4553, 4555, 4556, 4558, 4561, 4562, 4563, 4564, 4565, 4566, 4567, 4568, 4569, 4570, 4571, 4572, 4573, 4574, 4576, 4577, 4578, 4579, 4581, 4583, 4585, 4586, 4588, 4589, 4590, 4591, 4592, 4594, 4597, 4598, 4599, 4600, 4601, 4602, 4603, 4604, 4605, 4606, 4610, 4611, 4612, 4613, 4614, 4615, 4616, 4617, 4618, 4619, 4620, 4621, 4622, 4623, 4624, 4627, 4628, 4629, 4630, 4631, 4632, 4634, 4635, 4636, 4637, 4639, 4640, 4641, 4643, 4644, 4645, 4646, 4647, 4648, 4649, 4651, 4652, 4653, 4654, 4655, 4656, 4657, 4658, 4659, 4662, 4663, 4664, 4665, 4667, 4669, 4670, 4671, 4672, 4673, 4674, 4676, 4679, 4680, 4681, 4682, 4683, 4685, 4687, 4688, 4689, 4690, 4691, 4692, 4693, 4694, 4695, 4696, 4697, 4700, 4701, 4702, 4703, 4704, 4705, 4706, 4709, 4710, 4712, 4713, 4715, 4716, 4718, 4719, 4721, 4722, 4723, 4724, 4725, 4726, 4727, 4728, 4729, 4730, 4731, 4732, 4733, 4735, 4736, 4737, 4738, 4739, 4740, 4741, 4742, 4743, 4744, 4745, 4746, 4747, 4749, 4753, 4754, 4755, 4756, 4757, 4759, 4762, 4763, 4764, 4765, 4766, 4768, 4769, 4770, 4771, 4773, 4777, 4778, 4779, 4781, 4783, 4784, 4785, 4786, 4788, 4790, 4791, 4792, 4793, 4794, 4795, 4796, 4797, 4798, 4800, 4801, 4802, 4803, 4805, 4807, 4808, 4809, 4810, 4811, 4812, 4813, 4814, 4816, 4817, 4819, 4820, 4822, 4824, 4825, 4826, 4827, 4828, 4829, 4830, 4831, 4832, 4834, 4835, 4837, 4838, 4839, 4840, 4841, 4842, 4843, 4845, 4846, 4848, 4849, 4850, 4851, 4852, 4854, 4856, 4857, 4858, 4860, 4861, 4862, 4863, 4864, 4865, 4866, 4867, 4868, 4871, 4872, 4873, 4874, 4875, 4876, 4877, 4878, 4879, 4882, 4883, 4884, 4886, 4887, 4888, 4890, 4891, 4892, 4893, 4894, 4895, 4897, 4898, 4899, 4901, 4904, 4905, 4906, 4907, 4908, 4910, 4911, 4912, 4913, 4915, 4916, 4917, 4920, 4921, 4923, 4924, 4925, 4926, 4927, 4929, 4930, 4931, 4932, 4933, 4934, 4936, 4937, 4938, 4939, 4940, 4941, 4942, 4943, 4944, 4945, 4950, 4951, 4952, 4953, 4954, 4956, 4957, 4958, 4959, 4960, 4964, 4965, 4966, 4967, 4968, 4969, 4970, 4971, 4972, 4973, 4974, 4975, 4976, 4977, 4978, 4979, 4980, 4981, 4982, 4983, 4984, 4985, 4986, 4987, 4989, 4990, 4991, 4992, 4993, 4994, 4995, 4996, 4997, 4998, 4999, 5000, 5001, 5002, 5003, 5004, 5005, 5006, 5007, 5008, 5009, 5010, 5011, 5012, 5013, 5014, 5015, 5016, 5017, 5019, 5020, 5021, 5022, 5023, 5024, 5026, 5027, 5029, 5030, 5031, 5033, 5036, 5037, 5038, 5042, 5043, 5044, 5045, 5046, 5047, 5048, 5050, 5052, 5053, 5055, 5058, 5060, 5061, 5062, 5063, 5065, 5066, 5067, 5069, 5071, 5072, 5074, 5075, 5076, 5077, 5078, 5080, 5085, 5086, 5088, 5089, 5090, 5091, 5093, 5094, 5095, 5097, 5098, 5099, 5100, 5102, 5103, 5106, 5108, 5109, 5111, 5112, 5113, 5114, 5118, 5120, 5122, 5123, 5125, 5126, 5127, 5129, 5130, 5131, 5132, 5133, 5134, 5135, 5136, 5138, 5139, 5140, 5141, 5142, 5143, 5144, 5147, 5148, 5149, 5151, 5152, 5153, 5154, 5155, 5156, 5158, 5160, 5163, 5164, 5165, 5166, 5167, 5168, 5169, 5170, 5171, 5172, 5173, 5174, 5175, 5176, 5177, 5178, 5180, 5181, 5182, 5183, 5184, 5185, 5187, 5189, 5190, 5191, 5193, 5194, 5195, 5196, 5197, 5198, 5200, 5202, 5203, 5204, 5205, 5208, 5209, 5210, 5211, 5212, 5213, 5214, 5215, 5216, 5217, 5218, 5220, 5222, 5223, 5224, 5225, 5226, 5227, 5228, 5229, 5230, 5231, 5233, 5234, 5235, 5236, 5237, 5238, 5241, 5242, 5245, 5246, 5247, 5249, 5250, 5252, 5253, 5255, 5257, 5258, 5259, 5261, 5262, 5263, 5264, 5266, 5267, 5268, 5270, 5271, 5272, 5273, 5274, 5275, 5276, 5277, 5278, 5279, 5281, 5283, 5284, 5287, 5288, 5289, 5290, 5291, 5292, 5294, 5

In [33]:
#Convert all city names to uppercase and restore later
backup_city = sales_data['City'].copy()
sales_data['City'] = sales_data['City'].str.upper()
print(sales_data["City"])

#restore
sales_data['City'] = backup_city
print(sales_data["City"])

0             PHOENIX#123
1             HOUSTON#123
2            NEW YORK#123
3             CHICAGO#123
4             CHICAGO#123
               ...
100095            UNKNOWN
100096        CHICAGO#123
100097    LOS ANGELES#123
100098       NEW YORK#123
100099        CHICAGO#123
Name: City, Length: 100000, dtype: object
0             PHOENIX#123
1             HOUSTON#123
2            NEW YORK#123
3             CHICAGO#123
4             CHICAGO#123
               ...
100095            UNKNOWN
100096        CHICAGO#123
100097    LOS ANGELES#123
100098       NEW YORK#123
100099        CHICAGO#123
Name: City, Length: 100000, dtype: object

In [34]:
#Average price of each category
average_price = sales_data.groupby('Category')['Price'].mean()
print(average_price)

Category
Accessories    801.420981
Electronics    799.062436
Name: Price, dtype: float64

In [35]:
#Total sales by Region (groupby)
sales_sum=sales_data.groupby("Region")["TotalAmount"].sum()
print(sales_sum)

Region
East     99576789.10
North    98930659.21
South    99021836.16
West     98369402.78
Name: TotalAmount, dtype: float64

In [37]:
#Save only East region data to CSV
east_data=sales_data[sales_data["Region"]=="East"]
east_data.to_csv("east_region_data.csv",index=False)

In [40]:
#Reset and set index using OrderID
sales_reset = sales_data.reset_index()

sales_indexed = sales_data.set_index('OrderID')
print(sales_indexed)

         CustomerID CustomerName   Product     Category  Quantity    Price  \
OrderID
44770          8192  @ charlie !  Keyboard  Electronics       1.0   870.54
23355          9138  @ charlie !   Monitor  Electronics       5.0   144.02
75847          4098  @ charlie !    Laptop  Accessories       3.0   557.79
95176          2391      @ eva !   Monitor  Electronics       5.0   552.20
1854           8842      @ eva !    Laptop  Accessories       4.0   411.20
...             ...          ...       ...          ...       ...      ...
95426          5376    @ alice !  Keyboard  Electronics       2.0   468.67
77181          6047    @ alice !  Keyboard  Accessories       5.0  1350.58
7354           2439      @ bob !    Laptop  Electronics       8.0   330.46
52126          2810    @ alice !  Keyboard  Electronics       7.0   361.90
80766          5705    @ david !    Tablet  Electronics       1.0   760.99

         OrderDate             City Region  Returned  TotalAmount  UnitTotal  \
OrderID
44770          NaT      PHOENIX#123  South     False       870.54     870.54
23355   2024-05-02      HOUSTON#123   West     False       720.10     720.10
75847   2024-11-08     NEW YORK#123   East     False      1673.37    1673.37
95176          NaT      CHICAGO#123  North     False      2761.00    2761.00
1854           NaT      CHICAGO#123   East     False      1644.80    1644.80
...            ...              ...    ...       ...          ...        ...
95426   2023-08-14          UNKNOWN   West     False       937.34     937.34
77181          NaT      CHICAGO#123  South      True      6752.90    6752.90
7354    2024-10-05  LOS ANGELES#123   East     False      2643.68    2643.68
52126   2023-10-22     NEW YORK#123   West     False      2533.30    2533.30
80766   2023-03-26      CHICAGO#123  North     False       760.99     760.99

         DiscountApplied    Year  Month OrderMonth
OrderID
44770              False     NaN    NaN        NaN
23355              False  2024.0    5.0        May
75847              False  2024.0   11.0   November
95176              False     NaN    NaN        NaN
1854               False     NaN    NaN        NaN
...                  ...     ...    ...        ...
95426              False  2023.0    8.0     August
77181              False     NaN    NaN        NaN
7354               False  2024.0   10.0    October
52126              False  2023.0   10.0    October
80766              False  2023.0    3.0      March

[100000 rows x 16 columns]

In [41]:
#Display all weekend orders (Saturday & Sunday)
sales['Weekday'] = sales['OrderDate'].dt.weekday  # 0=Mon … 6=Sun
weekend_orders = sales[sales['Weekday'] >= 5]
weekend_orders

,OrderID,CustomerID,CustomerName,Product,Category,Quantity,Price,OrderDate,City,Region,Returned,TotalAmount,UnitTotal,Weekday
5,56788,6935,@ david !,Monitor,Electronics,1.0,415.12,2024-10-06,LOS ANGELES#123,West,False,415.12,415.12,6.0
7,79506,3389,@ alice !,Phone,Accessories,9.0,674.73,2024-07-14,HOUSTON#123,North,True,6072.57,6072.57,6.0
8,55148,1287,@ david !,Laptop,Accessories,2.0,330.38,2024-09-01,HOUSTON#123,East,False,660.76,660.76,6.0
9,24564,3745,@ bob !,Tablet,Accessories,8.0,686.34,2023-04-23,PHOENIX#123,North,False,5490.72,5490.72,6.0
10,60114,6368,@ alice !,Laptop,Accessories,3.0,512.79,2023-08-05,NEW YORK#123,North,False,1538.37,1538.37,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100090,87473,6459,@ eva !,Phone,Electronics,7.0,971.50,2023-12-10,PHOENIX#123,South,False,6800.50,6800.50,6.0
100091,46252,4130,@ bob !,Phone,Accessories,7.0,348.02,2024-06-01,CHICAGO#123,South,False,2436.14,2436.14,5.0
100097,7354,2439,@ bob !,Laptop,Electronics,8.0,330.46,2024-10-05,LOS ANGELES#123,East,False,2643.68,2643.68,5.0
100098,52126,2810,@ alice !,Keyboard,Electronics,7.0,361.90,2023-10-22,NEW YORK#123,West,False,2533.30,2533.30,6.0
100099,80766,5705,@ david !,Tablet,Electronics,1.0,760.99,2023-03-26,CHICAGO#123,North,False,760.99,760.99,6.0

In [43]:
#Create a pivot table of TotalAmount by Region and Category
pivot_region_category = sales_data.pivot_table(
    values='TotalAmount',
    index='Region',
    columns='Category',
    aggfunc='sum',
    fill_value=0
)
pivot_region_category

Category  Accessories  Electronics
Region
East      48596869.16  49141938.16
North     48243633.69  48498063.95
South     48628318.04  48338803.01
West      48250060.38  48238382.34

In [44]:
#Unpivot (melt) the pivot table from Task 31
melted = pivot_region_category.reset_index().melt(
    id_vars='Region',
    var_name='Category',
    value_name='TotalAmount'
)
melted

  Region     Category  TotalAmount
0   East  Accessories  48596869.16
1  North  Accessories  48243633.69
2  South  Accessories  48628318.04
3   West  Accessories  48250060.38
4   East  Electronics  49141938.16
5  North  Electronics  48498063.95
6  South  Electronics  48338803.01
7   West  Electronics  48238382.34

In [46]:
#Use groupby() to get average Price by Product and Region
avg_price_prod_region = sales.groupby(['Product', 'Region'])['Price'].mean()
avg_price_prod_region

Product   Region
Keyboard  East      792.978739
          North     800.111859
          South     802.419370
          West      792.614988
Laptop    East      804.949776
          North     814.811398
          South     801.517062
          West      793.726967
Monitor   East      802.803601
          North     788.955842
          South     793.167280
          West      803.838535
Phone     East      793.719012
          North     800.904670
          South     805.499545
          West      800.988814
Tablet    East      811.730826
          North     807.827802
          South     798.652803
          West      796.095443
Name: Price, dtype: float64

In [47]:
#Use .agg() to get min, max, mean Quantity for each Category
qty_stats_by_category = sales.groupby('Category')['Quantity'].agg(['min', 'max', 'mean'])
qty_stats_by_category

             min  max      mean
Category
Accessories  1.0  9.0  4.995743
Electronics  1.0  9.0  4.979949

In [48]:
#Create a lookup table for CustomerID and CustomerName and remove duplicates
customer_lookup = sales_data[['CustomerID', 'CustomerName']].drop_duplicates()
customer_lookup

        CustomerID CustomerName
0             8192  @ charlie !
1             9138  @ charlie !
2             4098  @ charlie !
3             2391      @ eva !
4             8842      @ eva !
...            ...          ...
100029        8276      @ bob !
100054        4222      @ eva !
100081        8960      @ bob !
100089        6732      @ eva !
100092        5466      @ eva !

[40134 rows x 2 columns]

In [49]:
#Create a lookup for Product and Category, remove duplicates
product_lookup = sales_data[['Product', 'Category']].drop_duplicates()
product_lookup

       Product     Category
0     Keyboard  Electronics
1      Monitor  Electronics
2       Laptop  Accessories
6       Tablet  Electronics
7        Phone  Accessories
9       Tablet  Accessories
11      Laptop  Electronics
14    Keyboard  Accessories
21       Phone  Electronics
32     Monitor  Accessories
77     Monitor          NaN
95         NaN  Accessories
127        NaN  Electronics
132     Tablet          NaN
151   Keyboard          NaN
240     Laptop          NaN
717      Phone          NaN
2207       NaN          NaN

In [50]:
#Merge back the lookups with the main file (simulate master lookup join)
merged_data = pd.merge(sales_data, customer_lookup, on='CustomerID', how='left')
merged_data = pd.merge(merged_data, product_lookup, on='Product', how='left')
merged_data

,OrderID,CustomerID,CustomerName_x,Product,Category_x,Quantity,Price,OrderDate,City,Region,Returned,TotalAmount,UnitTotal,DiscountApplied,Year,Month,OrderMonth,CustomerName_y,Category_y
0,44770,8192,@ charlie !,Keyboard,Electronics,1.0,870.54,NaT,PHOENIX#123,South,False,870.54,870.54,False,NaN,NaN,NaN,@ charlie !,Electronics
1,44770,8192,@ charlie !,Keyboard,Electronics,1.0,870.54,NaT,PHOENIX#123,South,False,870.54,870.54,False,NaN,NaN,NaN,@ charlie !,Accessories
2,44770,8192,@ charlie !,Keyboard,Electronics,1.0,870.54,NaT,PHOENIX#123,South,False,870.54,870.54,False,NaN,NaN,NaN,@ charlie !,NaN
3,44770,8192,@ charlie !,Keyboard,Electronics,1.0,870.54,NaT,PHOENIX#123,South,False,870.54,870.54,False,NaN,NaN,NaN,@ eva !,Electronics
4,44770,8192,@ charlie !,Keyboard,Electronics,1.0,870.54,NaT,PHOENIX#123,South,False,870.54,870.54,False,NaN,NaN,NaN,@ eva !,Accessories
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1369468,80766,5705,@ david !,Tablet,Electronics,1.0,760.99,2023-03-26,CHICAGO#123,North,False,760.99,760.99,False,2023.0,3.0,March,@ eva !,Accessories
1369469,80766,5705,@ david !,Tablet,Electronics,1.0,760.99,2023-03-26,CHICAGO#123,North,False,760.99,760.99,False,2023.0,3.0,March,@ eva !,NaN
1369470,80766,5705,@ david !,Tablet,Electronics,1.0,760.99,2023-03-26,CHICAGO#123,North,False,760.99,760.99,False,2023.0,3.0,March,@ alice !,Electronics
1369471,80766,5705,@ david !,Tablet,Electronics,1.0,760.99,2023-03-26,CHICAGO#123,North,False,760.99,760.99,False,2023.0,3.0,March,@ alice !,Accessories
1369472,80766,5705,@ david !,Tablet,Electronics,1.0,760.99,2023-03-26,CHICAGO#123,North,False,760.99,760.99,False,2023.0,3.0,March,@ alice !,NaN

In [51]:
#Calculate return rate % by region
return_rate_by_region = sales_data.groupby('Region')['Returned'].mean() * 100
return_rate_by_region

Region
East     10.092438
North     9.783391
South     9.752780
West      9.826381
Name: Returned, dtype: float64

In [52]:
#Create a new column DiscountedPrice assuming a flat 10% discount on all products
sales_data['DiscountedPrice'] = sales_data['Price'] * 0.9
sales_data

,OrderID,CustomerID,CustomerName,Product,Category,Quantity,Price,OrderDate,City,Region,Returned,TotalAmount,UnitTotal,DiscountApplied,Year,Month,OrderMonth,DiscountedPrice
0,44770,8192,@ charlie !,Keyboard,Electronics,1.0,870.54,NaT,PHOENIX#123,South,False,870.54,870.54,False,NaN,NaN,NaN,783.486
1,23355,9138,@ charlie !,Monitor,Electronics,5.0,144.02,2024-05-02,HOUSTON#123,West,False,720.10,720.10,False,2024.0,5.0,May,129.618
2,75847,4098,@ charlie !,Laptop,Accessories,3.0,557.79,2024-11-08,NEW YORK#123,East,False,1673.37,1673.37,False,2024.0,11.0,November,502.011
3,95176,2391,@ eva !,Monitor,Electronics,5.0,552.20,NaT,CHICAGO#123,North,False,2761.00,2761.00,False,NaN,NaN,NaN,496.980
4,1854,8842,@ eva !,Laptop,Accessories,4.0,411.20,NaT,CHICAGO#123,East,False,1644.80,1644.80,False,NaN,NaN,NaN,370.080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100095,95426,5376,@ alice !,Keyboard,Electronics,2.0,468.67,2023-08-14,UNKNOWN,West,False,937.34,937.34,False,2023.0,8.0,August,421.803
100096,77181,6047,@ alice !,Keyboard,Accessories,5.0,1350.58,NaT,CHICAGO#123,South,True,6752.90,6752.90,False,NaN,NaN,NaN,1215.522
100097,7354,2439,@ bob !,Laptop,Electronics,8.0,330.46,2024-10-05,LOS ANGELES#123,East,False,2643.68,2643.68,False,2024.0,10.0,October,297.414
100098,52126,2810,@ alice !,Keyboard,Electronics,7.0,361.90,2023-10-22,NEW YORK#123,West,False,2533.30,2533.30,False,2023.0,10.0,October,325.710
100099,80766,5705,@ david !,Tablet,Electronics,1.0,760.99,2023-03-26,CHICAGO#123,North,False,760.99,760.99,False,2023.0,3.0,March,684.891

In [54]:
#Calculate the cumulative revenue for each Region sorted by OrderDate
sales_data = sales_data.sort_values(['Region', 'OrderDate'])
sales_data['CumulativeRevenue'] = sales_data.groupby('Region')['TotalAmount'].cumsum()
sales_data['CumulativeRevenue']

6766           778.08
11608         7677.54
13730        11979.90
17594        14834.78
17652        17252.90
             ...
99997     98358302.98
100013    98362231.27
100048    98362741.59
100080    98363837.63
100084    98369402.78
Name: CumulativeRevenue, Length: 100000, dtype: float64

In [56]:
#Rank customers by their total revenue generated (TotalAmount) in descending order
customer_rank = sales_data.groupby('CustomerID')['TotalAmount'].sum().reset_index()
customer_rank['Rank'] = customer_rank['TotalAmount'].rank(ascending=False, method='min')
customer_rank.head(20)

    CustomerID  TotalAmount    Rank
0         1000     46434.37  3652.0
1         1001     43657.82  4234.0
2         1002     26351.27  7735.0
3         1003     40095.51  5022.0
4         1004     20623.99  8388.0
5         1005     48673.73  3196.0
6         1006     58988.01  1618.0
7         1007     44664.16  4006.0
8         1008     27927.57  7511.0
9         1009     37690.88  5579.0
10        1010     41778.69  4649.0
11        1011     74857.04   421.0
12        1012     46828.70  3565.0
13        1013     39714.72  5109.0
14        1014     41252.53  4770.0
15        1015     24963.22  7937.0
16        1016     62266.72  1274.0
17        1017     42515.72  4475.0
18        1018     50271.35  2899.0
19        1019     37375.26  5654.0

In [57]:
#Calculate the average order value per customer using groupby()
average_order_value = sales_data.groupby('CustomerID')['TotalAmount'].mean()
average_order_value

CustomerID
1000    3316.740714
1001    2728.613750
1002    3293.908750
1003    2863.965000
1004    2291.554444
           ...
9994    4331.444375
9995    4778.646190
9996    4078.016364
9997    4062.555000
9998    5318.008421
Name: TotalAmount, Length: 8999, dtype: float64

In [58]:
#Generate a report showing total quantity sold per Category per Region
quantity_report = sales_data.groupby(['Region', 'Category'])['Quantity'].sum().reset_index()
quantity_report

  Region     Category  Quantity
0   East  Accessories   60655.0
1   East  Electronics   61020.0
2  North  Accessories   60266.0
3  North  Electronics   60393.0
4  South  Accessories   60689.0
5  South  Electronics   60429.0
6   West  Accessories   59860.0
7   West  Electronics   60548.0

In [59]:
#Use .agg() to compute multiple stats (sum, mean, min, max) for TotalAmount per Region
region_stats = sales.groupby('Region')['TotalAmount'].agg(['sum','mean','min','max']).reset_index()
region_stats

  Region          sum         mean     min       max
0   East  99725660.81  4007.460752  100.07  13492.53
1  North  99066474.71  3997.839980  100.19  13491.45
2  South  99089901.41  4001.368980  101.10  13492.80
3   West  98470580.60  3991.511171  100.34  13499.91

In [60]:
#Create a summary DataFrame showing each customer’s: total orders, total amount spent, and total products bought
customer_summary = sales_data.groupby('CustomerID').agg(
    TotalOrders=('OrderID', 'nunique'),
    TotalAmount=('TotalAmount', 'sum'),
    TotalProducts=('Quantity', 'sum')
).reset_index()
customer_summary

      CustomerID  TotalOrders  TotalAmount  TotalProducts
0           1000           14     46434.37           61.0
1           1001           16     43657.82           71.0
2           1002            8     26351.27           38.0
3           1003           14     40095.51           60.0
4           1004            9     20623.99           39.0
...          ...          ...          ...            ...
8994        9994           16     69303.11           71.0
8995        9995           21    100351.57          111.0
8996        9996           11     44858.18           53.0
8997        9997            8     32500.44           42.0
8998        9998           20    101042.16          111.0

[8999 rows x 4 columns]

In [62]:
#onvert OrderDate to datetime and extract Year, Month, and Weekday
sales['OrderDate'] = pd.to_datetime(sales['OrderDate'])
sales['Year'] = sales['OrderDate'].dt.year
sales['Month'] = sales['OrderDate'].dt.month
sales['Weekday'] = sales['OrderDate'].dt.day_name()
sales[['OrderDate','Year','Month','Weekday']].head(10)

   OrderDate    Year  Month    Weekday
0        NaT     NaN    NaN        NaN
1 2024-05-02  2024.0    5.0   Thursday
2 2024-11-08  2024.0   11.0     Friday
3        NaT     NaN    NaN        NaN
4        NaT     NaN    NaN        NaN
5 2024-10-06  2024.0   10.0     Sunday
6 2024-04-03  2024.0    4.0  Wednesday
7 2024-07-14  2024.0    7.0     Sunday
8 2024-09-01  2024.0    9.0     Sunday
9 2023-04-23  2023.0    4.0     Sunday

In [66]:
#Extract only the first name from CustomerName
sales_data['FirstName'] = sales_data['CustomerName'].str.split().str[0]
sales_data['FirstName']

6766      @
11608     @
13730     @
17594     @
17652     @
         ..
99997     @
100013    @
100048    @
100080    @
100084    @
Name: FirstName, Length: 100000, dtype: object

In [67]:
#Extract only the first name from CustomerName
sales_data['FirstName'] = sales_data['CustomerName'].str.split().str[0]
sales_data['FirstName']

6766      @
11608     @
13730     @
17594     @
17652     @
         ..
99997     @
100013    @
100048    @
100080    @
100084    @
Name: FirstName, Length: 100000, dtype: object

In [68]:
#Create HighValueOrder where TotalAmount > 5000
sales_data['HighValueOrder'] = sales_data['TotalAmount'] > 5000
sales_data['HighValueOrder']

6766      False
11608      True
13730     False
17594     False
17652     False
          ...
99997     False
100013    False
100048    False
100080    False
100084     True
Name: HighValueOrder, Length: 100000, dtype: bool

In [70]:
#Analyze & visualize top 5 customers and top 5 products contributing to revenue using master file

top_customers = sales_data.groupby('CustomerName')['TotalAmount'].sum().sort_values(ascending=False).head(5).reset_index()
top_products = sales_data.groupby('Product')['TotalAmount'].sum().sort_values(ascending=False).head(5).reset_index()
top_customers, top_products

(  CustomerName  TotalAmount
 0      @ bob !  80792023.58
 1      @ eva !  79699296.25
 2    @ alice !  78661034.98
 3    @ david !  78453964.56
 4  @ charlie !  78292367.88,
     Product  TotalAmount
 0    Laptop  78531807.54
 1     Phone  78132514.71
 2    Tablet  77839753.89
 3  Keyboard  77172965.77
 4   Monitor  76437165.84)